#import <AppKit/AppKit.h>
#import "SonosLANClient.h"

@interface VolumeCell:NSSliderCell
@end
@implementation VolumeCell
-(void)drawBarInside:(NSRect)rect flipped:(BOOL)flipped{NSRect b=self.controlView.bounds;CGFloat x=7,width=b.size.width-14,y=NSMidY(b)-1.5;[[NSColor.labelColor colorWithAlphaComponent:0.25]setFill];[[NSBezierPath bezierPathWithRoundedRect:NSMakeRect(x,y,width,3) xRadius:1.5 yRadius:1.5]fill];[[NSColor.labelColor colorWithAlphaComponent:self.enabled?1:0.4]setFill];CGFloat fraction=(self.doubleValue-self.minValue)/MAX(1,self.maxValue-self.minValue);[[NSBezierPath bezierPathWithRoundedRect:NSMakeRect(x,y,width*MAX(0,MIN(1,fraction)),3) xRadius:1.5 yRadius:1.5]fill];}
-(void)drawKnob:(NSRect)rect{NSRect b=self.controlView.bounds;CGFloat fraction=(self.doubleValue-self.minValue)/MAX(1,self.maxValue-self.minValue),x=7+(b.size.width-14)*MAX(0,MIN(1,fraction));[[NSColor.labelColor colorWithAlphaComponent:self.enabled?1:0.4]setFill];[[NSBezierPath bezierPathWithOvalInRect:NSMakeRect(x-5,NSMidY(b)-5,10,10)]fill];}
@end
@interface CardView:NSView
@end
@implementation CardView
-(BOOL)isFlipped{return YES;}
-(void)viewDidChangeEffectiveAppearance{[super viewDidChangeEffectiveAppearance];self.needsDisplay=YES;for(NSView*v in self.subviews){v.needsDisplay=YES;if([v isKindOfClass:NSImageView.class])v.layer.backgroundColor=NSColor.quaternaryLabelColor.CGColor;}}
-(void)drawRect:(NSRect)dirty{[NSColor.windowBackgroundColor setFill];[[NSBezierPath bezierPathWithRoundedRect:self.bounds xRadius:22 yRadius:22]fill];}
@end
@interface SonosController:NSObject<NSApplicationDelegate>
@property NSStatusItem*item;@property NSPopover*popover;@property CardView*card;
@property NSTextField*room;@property NSTextField*track;@property NSTextField*artist;@property NSTextField*volumeText;
@property NSImageView*cover;@property NSSlider*volume;@property NSButton*play;@property NSButton*previous;@property NSButton*next;
@property NSDictionary*state;@property SonosLANClient*api;@property BOOL diagnostics;@property BOOL refreshing;@property NSString*artURL;@property NSURLSessionDataTask*artTask;@property NSURLSession*session;@property NSCache*images;@property NSDate*retryAfter;
@end
@implementation SonosController
-(NSTextField*)label:(NSRect)frame size:(CGFloat)size weight:(NSFontWeight)weight{NSTextField*l=[NSTextField labelWithString:@""];l.frame=frame;l.font=[NSFont systemFontOfSize:size weight:weight];l.textColor=NSColor.labelColor;l.lineBreakMode=NSLineBreakByTruncatingTail;l.maximumNumberOfLines=1;[self.card addSubview:l];return l;}
-(NSButton*)button:(NSString*)symbol label:(NSString*)label frame:(NSRect)frame action:(SEL)action{NSButton*b=[NSButton buttonWithImage:[NSImage imageWithSystemSymbolName:symbol accessibilityDescription:label] target:self action:action];b.frame=frame;b.bordered=NO;b.contentTintColor=NSColor.labelColor;b.toolTip=label;b.accessibilityLabel=label;[self.card addSubview:b];return b;}
-(void)applicationDidFinishLaunching:(NSNotification*)n{[NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];self.api=[SonosLANClient new];self.images=[NSCache new];self.images.totalCostLimit=8*1024*1024;NSURLSessionConfiguration*c=NSURLSessionConfiguration.defaultSessionConfiguration;c.timeoutIntervalForRequest=12;NSURL*cache=[[[NSFileManager.defaultManager URLsForDirectory:NSCachesDirectory inDomains:NSUserDomainMask].firstObject URLByAppendingPathComponent:@"local.ops.sonos-controller" isDirectory:YES]URLByAppendingPathComponent:@"AlbumArt" isDirectory:YES];[NSFileManager.defaultManager createDirectoryAtURL:cache withIntermediateDirectories:YES attributes:nil error:nil];c.URLCache=[[NSURLCache alloc]initWithMemoryCapacity:4*1024*1024 diskCapacity:24*1024*1024 directoryURL:cache];self.session=[NSURLSession sessionWithConfiguration:c];self.item=[NSStatusBar.systemStatusBar statusItemWithLength:44];NSImage*icon=[[NSImage alloc]initWithContentsOfURL:[NSBundle.mainBundle URLForResource:@"sonos-menubar" withExtension:@"png"]];icon.template=YES;icon.size=NSMakeSize(44,18);self.item.button.image=icon;self.item.button.toolTip=@"Sonos";self.item.button.target=self;self.item.button.action=@selector(show:);
self.card=[[CardView alloc]initWithFrame:NSMakeRect(0,0,420,184)];self.room=[self label:NSMakeRect(20,20,300,26) size:19 weight:NSFontWeightSemibold];self.room.stringValue=@"Your System";
[self button:@"arrow.up.right.square" label:@"Open Sonos" frame:NSMakeRect(340,18,28,28) action:@selector(open:)];[self button:@"power" label:@"Exit controller" frame:NSMakeRect(378,18,28,28) action:@selector(exit:)];
self.cover=[[NSImageView alloc]initWithFrame:NSMakeRect(20,65,52,52)];self.cover.imageScaling=NSImageScaleProportionallyUpOrDown;self.cover.wantsLayer=YES;self.cover.layer.cornerRadius=4;self.cover.layer.masksToBounds=YES;self.cover.layer.backgroundColor=NSColor.quaternaryLabelColor.CGColor;self.cover.accessibilityLabel=@"Current album artwork";[self.card addSubview:self.cover];self.track=[self label:NSMakeRect(84,66,196,23) size:15 weight:NSFontWeightMedium];self.artist=[self label:NSMakeRect(84,91,196,20) size:13 weight:NSFontWeightRegular];self.artist.textColor=NSColor.secondaryLabelColor;self.previous=[self button:@"backward.end.fill" label:@"Previous track" frame:NSMakeRect(281,77,27,28) action:@selector(previous:)];self.play=[self button:@"play.circle.fill" label:@"Play or pause" frame:NSMakeRect(313,65,49,49) action:@selector(play:)];self.play.image=[self.play.image imageWithSymbolConfiguration:[NSImageSymbolConfiguration configurationWithPointSize:35 weight:NSFontWeightRegular]];self.next=[self button:@"forward.end.fill" label:@"Next track" frame:NSMakeRect(372,77,27,28) action:@selector(next:)];
[self button:@"speaker.wave.2" label:@"Volume" frame:NSMakeRect(19,137,24,25) action:@selector(mute:)];self.volume=[NSSlider sliderWithValue:0 minValue:0 maxValue:100 target:self action:@selector(volume:)];VolumeCell *cell=[VolumeCell new];cell.minValue=0;cell.maxValue=100;cell.target=self;cell.action=@selector(volume:);self.volume.cell=cell;self.volume.frame=NSMakeRect(54,138,307,23);self.volume.continuous=NO;self.volume.accessibilityLabel=@"Sonos volume";[self.card addSubview:self.volume];self.volumeText=[self label:NSMakeRect(370,139,35,20) size:13 weight:NSFontWeightMedium];self.volumeText.alignment=NSTextAlignmentRight;
NSViewController*vc=[NSViewController new];vc.view=self.card;self.popover=[NSPopover new];self.popover.contentViewController=vc;self.popover.contentSize=self.card.frame.size;self.popover.behavior=NSPopoverBehaviorTransient;self.popover.animates=YES;[self refresh];NSTimer *timer=[NSTimer timerWithTimeInterval:1 target:self selector:@selector(tick:) userInfo:nil repeats:YES];[NSRunLoop.mainRunLoop addTimer:timer forMode:NSRunLoopCommonModes];}
-(void)tick:(NSTimer*)t{static int count=0;if(self.popover.shown||++count%3==0)[self refresh];}
-(BOOL)applicationShouldHandleReopen:(NSApplication*)app hasVisibleWindows:(BOOL)flag{[self show:nil];return YES;}
-(void)show:(id)sender{if(self.popover.shown){[self.popover close];return;}[self refresh];[NSApp activateIgnoringOtherApps:YES];[self.popover showRelativeToRect:self.item.button.bounds ofView:self.item.button preferredEdge:NSRectEdgeMinY];}
-(void)open:(id)sender{[self.popover close];[NSWorkspace.sharedWorkspace openURL:[NSURL fileURLWithPath:[NSHomeDirectory()stringByAppendingPathComponent:@"Applications/Sonos.app"]]];}
-(void)exit:(id)sender{[self.artTask cancel];[NSApp terminate:nil];}
-(void)refresh{if(self.refreshing)return;self.refreshing=YES;[self.api fetchState:^(NSDictionary*s){self.refreshing=NO;self.state=s;BOOL ready=!s[@"error"];self.room.stringValue=s[@"room"]?:@"Your System";self.track.stringValue=s[@"track"]?:s[@"error"];self.artist.stringValue=s[@"artist"]?:@"";self.track.toolTip=self.track.stringValue;self.artist.toolTip=self.artist.stringValue;self.play.enabled=ready&&[s[@"toggle"]boolValue];self.previous.enabled=[s[@"previous"]boolValue];self.next.enabled=[s[@"next"]boolValue];self.volume.enabled=[s[@"slider"]boolValue];self.volume.doubleValue=[s[@"volume"]doubleValue];self.volumeText.stringValue=s[@"volume"]?[NSString stringWithFormat:@"%.0f",self.volume.doubleValue]:@"—";NSString*symbol=[s[@"playing"]boolValue]?@"pause.circle.fill":@"play.circle.fill";self.play.image=[[NSImage imageWithSystemSymbolName:symbol accessibilityDescription:@"Play or pause"]imageWithSymbolConfiguration:[NSImageSymbolConfiguration configurationWithPointSize:35 weight:NSFontWeightRegular]];[self updateArt:s[@"art"]?:@""];if(self.diagnostics){NSDictionary*status=@{@"pid":@(NSProcessInfo.processInfo.processIdentifier),@"source":@"Sonos LAN API",@"error":s[@"error"]?:@"",@"room":self.room.stringValue,@"track":self.track.stringValue,@"artist":self.artist.stringValue,@"volume":s[@"volume"]?:@0,@"playing":s[@"playing"]?:@NO,@"artLoaded":@(self.cover.image!=nil)};NSData*json=[NSJSONSerialization dataWithJSONObject:status options:NSJSONWritingPrettyPrinted error:nil];[json writeToFile:@"/private/tmp/sonos-lan-live-status.json" options:NSDataWritingAtomic error:nil];[NSFileManager.defaultManager setAttributes:@{NSFilePosixPermissions:@0600} ofItemAtPath:@"/private/tmp/sonos-lan-live-status.json" error:nil];} }];}
-(void)updateArt:(NSString*)url{BOOL changed=![url isEqual:self.artURL];if(changed){[self.artTask cancel];self.artTask=nil;self.artURL=url;self.cover.image=nil;self.retryAfter=nil;}if(!url.length||self.artTask||(!changed&&self.cover.image)||(self.retryAfter&&self.retryAfter.timeIntervalSinceNow>0))return;NSImage*cached=[self.images objectForKey:url];if(cached){self.cover.image=cached;return;}NSURL*u=[NSURL URLWithString:url];if(![u.scheme isEqual:@"https"]&&![SonosLANClient isLocalURL:u])return;NSURLRequest*r=[NSURLRequest requestWithURL:u cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:12];self.artTask=[self.session dataTaskWithRequest:r completionHandler:^(NSData*data,NSURLResponse*response,NSError*error){NSImage*image=nil;if(!error&&data.length<5*1024*1024&&[(NSHTTPURLResponse*)response statusCode]==200&&[response.MIMEType hasPrefix:@"image/"])image=[[NSImage alloc]initWithData:data];dispatch_async(dispatch_get_main_queue(),^{if(![self.artURL isEqual:url])return;self.artTask=nil;if(image){self.cover.image=image;[self.images setObject:image forKey:url cost:data.length];}else self.retryAfter=[NSDate dateWithTimeIntervalSinceNow:30];});}];[self.artTask resume];}
-(void)action:(NSString*)key value:(NSNumber*)value{self.play.enabled=NO;self.previous.enabled=NO;self.next.enabled=NO;[self.api performAction:key value:value completion:^(NSString*error){if(error)self.artist.stringValue=error;[self refresh];}];}
-(void)play:(id)s{[self action:@"toggle" value:nil];}
-(void)previous:(id)s{[self action:@"previous" value:nil];}
-(void)next:(id)s{[self action:@"next" value:nil];}
-(void)volume:(id)sender{self.volumeText.stringValue=[NSString stringWithFormat:@"%.0f",self.volume.doubleValue];[self action:@"volume" value:@(self.volume.integerValue)];}
-(void)mute:(id)sender{[self action:@"mute" value:nil];}

@end
int main(int argc,const char*argv[]){@autoreleasepool{[NSApplication sharedApplication];if(argc>1&&!strcmp(argv[1],"--read-state")){SonosLANClient*api=[SonosLANClient new];__block BOOL done=NO;[api fetchState:^(NSDictionary*s){NSData*json=[NSJSONSerialization dataWithJSONObject:@{@"source":@"Sonos LAN API",@"error":s[@"error"]?:@"",@"room":s[@"room"]?:@"",@"track":s[@"track"]?:@"",@"artist":s[@"artist"]?:@"",@"playing":s[@"playing"]?:@NO,@"volume":s[@"volume"]?:@0,@"artworkAvailable":@([s[@"art"]length]>0)} options:NSJSONWritingPrettyPrinted error:nil];puts([[NSString alloc]initWithData:json encoding:NSUTF8StringEncoding].UTF8String);done=YES;}];NSDate*end=[NSDate dateWithTimeIntervalSinceNow:30];while(!done&&end.timeIntervalSinceNow>0)[NSRunLoop.mainRunLoop runUntilDate:[NSDate dateWithTimeIntervalSinceNow:0.05]];return done?0:1;}NSApplication*app=NSApplication.sharedApplication;SonosController*c=[SonosController new];c.diagnostics=[NSProcessInfo.processInfo.arguments containsObject:@"--diagnostics"];app.delegate=c;[app run];}return 0;}
