#import "SonosLANClient.h"
#import <sys/socket.h>
#import <arpa/inet.h>
#import <unistd.h>

@interface SonosXMLNode : NSObject
@property NSString *name;
@property NSMutableString *text;
@property NSDictionary *attributes;
@property NSMutableArray<SonosXMLNode *> *children;
- (nullable SonosXMLNode *)first:(NSString *)name;
- (NSArray<SonosXMLNode *> *)all:(NSString *)name;
@end
@implementation SonosXMLNode
- (SonosXMLNode *)first:(NSString *)name { if([self.name isEqual:name])return self;for(SonosXMLNode *n in self.children){SonosXMLNode *found=[n first:name];if(found)return found;}return nil; }
- (NSArray<SonosXMLNode *> *)all:(NSString *)name { NSMutableArray *a=[NSMutableArray array];if([self.name isEqual:name])[a addObject:self];for(SonosXMLNode *n in self.children)[a addObjectsFromArray:[n all:name]];return a; }
@end
@interface SonosXMLParser : NSObject<NSXMLParserDelegate>
@property SonosXMLNode *root;
@property NSMutableArray<SonosXMLNode *> *stack;
@end
@implementation SonosXMLParser
- (void)parser:(NSXMLParser *)p didStartElement:(NSString *)name namespaceURI:(NSString *)uri qualifiedName:(NSString *)q attributes:(NSDictionary *)attributes { SonosXMLNode *n=[SonosXMLNode new];n.name=[name componentsSeparatedByString:@":"].lastObject;n.attributes=attributes;n.text=[NSMutableString string];n.children=[NSMutableArray array];if(self.stack.count)[self.stack.lastObject.children addObject:n];else self.root=n;[self.stack addObject:n]; }
- (void)parser:(NSXMLParser *)p foundCharacters:(NSString *)text { [self.stack.lastObject.text appendString:text]; }
- (void)parser:(NSXMLParser *)p didEndElement:(NSString *)name namespaceURI:(NSString *)uri qualifiedName:(NSString *)q { [self.stack removeLastObject]; }
@end
static SonosXMLNode *ParseXML(NSData *data) { if(!data.length||data.length>1024*1024)return nil;SonosXMLParser *delegate=[SonosXMLParser new];delegate.stack=[NSMutableArray array];NSXMLParser *parser=[[NSXMLParser alloc]initWithData:data];parser.shouldResolveExternalEntities=NO;parser.delegate=delegate;return [parser parse]?delegate.root:nil; }
static NSString *Text(SonosXMLNode *node,NSString *name) { return [[node first:name].text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]?:@""; }
static NSString *Escape(NSString *s) { return [[[s stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]stringByReplacingOccurrencesOfString:@"<" withString:@"&lt;"]stringByReplacingOccurrencesOfString:@">" withString:@"&gt;"]; }

@interface SonosLANClient ()
@property dispatch_queue_t worker;
@property NSURLSession *session;
@property NSURL *deviceURL;
@property NSURL *coordinatorURL;
@property NSString *room;
@property NSString *uuid;
@property NSDate *topologyReadAt;
@property NSDate *nextDiscoveryAt;
@property NSMutableDictionary<NSString *,NSString *> *services;
@end
@implementation SonosLANClient
+ (BOOL)isLocalURL:(NSURL *)url { struct in_addr addr;if(![url.scheme isEqual:@"http"]||inet_pton(AF_INET,url.host.UTF8String,&addr)!=1)return NO;uint32_t n=ntohl(addr.s_addr);return (n>>24)==10||(n>>16)==0xc0a8||(n>>20)==0xac1||(n>>16)==0xa9fe; }
- (instancetype)init { if((self=[super init])){self.worker=dispatch_queue_create("local.ops.sonos-lan",DISPATCH_QUEUE_SERIAL);NSURLSessionConfiguration *c=NSURLSessionConfiguration.ephemeralSessionConfiguration;c.timeoutIntervalForRequest=3;c.timeoutIntervalForResource=4;c.requestCachePolicy=NSURLRequestReloadIgnoringLocalCacheData;c.connectionProxyDictionary=@{};self.session=[NSURLSession sessionWithConfiguration:c];self.services=[NSMutableDictionary dictionary];}return self; }
// Blocking waits are confined to the serial network worker, never the AppKit thread.
- (NSData *)request:(NSURLRequest *)request { dispatch_semaphore_t done=dispatch_semaphore_create(0);__block NSData *received;NSURLSessionDataTask *task=[self.session dataTaskWithRequest:request completionHandler:^(NSData *data,NSURLResponse *response,NSError *error){if(!error&&[(NSHTTPURLResponse *)response statusCode]==200&&data.length<=1024*1024)received=data;dispatch_semaphore_signal(done);}];[task resume];if(dispatch_semaphore_wait(done,dispatch_time(DISPATCH_TIME_NOW,5*NSEC_PER_SEC))){[task cancel];return nil;}return received; }
- (SonosXMLNode *)soap:(NSString *)action service:(NSString *)service base:(NSURL *)base arguments:(NSDictionary *)arguments { NSString *path=self.services[service];if(!path.length||!base)return nil;NSMutableString *args=[NSMutableString string];for(NSString *key in arguments)[args appendFormat:@"<%@>%@</%@>",key,Escape([arguments[key] description]),key];NSString *xml=[NSString stringWithFormat:@"<?xml version=\"1.0\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:%@ xmlns:u=\"%@\">%@</u:%@></s:Body></s:Envelope>",action,service,args,action];NSURL *url=[NSURL URLWithString:path relativeToURL:base].absoluteURL;if(![SonosLANClient isLocalURL:url])return nil;NSMutableURLRequest *r=[NSMutableURLRequest requestWithURL:url];r.HTTPMethod=@"POST";r.HTTPBody=[xml dataUsingEncoding:NSUTF8StringEncoding];[r setValue:@"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];[r setValue:[NSString stringWithFormat:@"\"%@#%@\"",service,action] forHTTPHeaderField:@"SOAPACTION"];return ParseXML([self request:r]); }
- (BOOL)loadDevice:(NSURL *)url { if(![SonosLANClient isLocalURL:url]||url.port.integerValue!=1400)return NO;SonosXMLNode *description=ParseXML([self request:[NSURLRequest requestWithURL:url]]);if(![Text(description,@"manufacturer").lowercaseString containsString:@"sonos"])return NO;self.deviceURL=url;self.coordinatorURL=url;self.room=Text(description,@"roomName");self.uuid=[Text(description,@"UDN") stringByReplacingOccurrencesOfString:@"uuid:" withString:@""];[self.services removeAllObjects];for(SonosXMLNode *service in [description all:@"service"]){NSString *type=Text(service,@"serviceType"),*path=Text(service,@"controlURL");if(type.length&&path.length)self.services[type]=path;}self.topologyReadAt=nil;return self.services[@"urn:schemas-upnp-org:service:AVTransport:1"]!=nil; }
- (NSArray<NSURL *> *)discover { int fd=socket(AF_INET,SOCK_DGRAM,IPPROTO_UDP);if(fd<0)return @[];struct timeval receiveTimeout={.tv_sec=0,.tv_usec=250000};setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&receiveTimeout,sizeof(receiveTimeout));struct sockaddr_in dest={0};dest.sin_family=AF_INET;dest.sin_port=htons(1900);inet_pton(AF_INET,"239.255.255.250",&dest.sin_addr);const char *message="M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: \"ssdp:discover\"\r\nMX: 2\r\nST: urn:schemas-upnp-org:device:ZonePlayer:1\r\n\r\n";sendto(fd,message,strlen(message),0,(struct sockaddr *)&dest,sizeof(dest));NSMutableOrderedSet *locations=[NSMutableOrderedSet orderedSet];NSDate *end=[NSDate dateWithTimeIntervalSinceNow:2.5];while(end.timeIntervalSinceNow>0){char bytes[8192];ssize_t count=recv(fd,bytes,sizeof(bytes),0);if(count<=0)continue;NSString *reply=[[NSString alloc]initWithBytes:bytes length:count encoding:NSUTF8StringEncoding];for(NSString *line in [reply componentsSeparatedByCharactersInSet:NSCharacterSet.newlineCharacterSet]){if([line.lowercaseString hasPrefix:@"location:"]){NSURL *u=[NSURL URLWithString:[[line substringFromIndex:9]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]];if([SonosLANClient isLocalURL:u]&&u.port.integerValue==1400)[locations addObject:u];}}}close(fd);return locations.array; }
- (BOOL)ensureDevice { if(self.deviceURL)return YES;if(self.nextDiscoveryAt.timeIntervalSinceNow>0)return NO;NSString *cached=[NSUserDefaults.standardUserDefaults stringForKey:@"LANDeviceLocation"];NSURL *known=cached.length?[NSURL URLWithString:cached]:nil;if(known&&[self loadDevice:known])return YES;for(NSURL *u in [self discover])if([self loadDevice:u]){if(NSBundle.mainBundle.bundleIdentifier.length)[NSUserDefaults.standardUserDefaults setObject:u.absoluteString forKey:@"LANDeviceLocation"];return YES;}self.nextDiscoveryAt=[NSDate dateWithTimeIntervalSinceNow:10];return NO; }
- (void)updateCoordinator { if(self.topologyReadAt&&-self.topologyReadAt.timeIntervalSinceNow<30)return;SonosXMLNode *response=[self soap:@"GetZoneGroupState" service:@"urn:schemas-upnp-org:service:ZoneGroupTopology:1" base:self.deviceURL arguments:@{}];SonosXMLNode *groups=ParseXML([Text(response,@"ZoneGroupState")dataUsingEncoding:NSUTF8StringEncoding]);for(SonosXMLNode *group in [groups all:@"ZoneGroup"]){NSArray *members=[group all:@"ZoneGroupMember"];BOOL belongs=NO;for(SonosXMLNode *member in members)if([member.attributes[@"UUID"]isEqual:self.uuid])belongs=YES;if(!belongs)continue;NSString *coordinator=group.attributes[@"Coordinator"];for(SonosXMLNode *member in members){if([member.attributes[@"UUID"]isEqual:coordinator]){NSURL *url=[NSURL URLWithString:member.attributes[@"Location"]];if([SonosLANClient isLocalURL:url]&&url.port.integerValue==1400)self.coordinatorURL=url;}}}self.topologyReadAt=[NSDate date]; }
- (NSDictionary *)read { if(![self ensureDevice])return @{@"error":@"Connect to the same Wi-Fi as your Sonos"};[self updateCoordinator];NSString *transport=@"urn:schemas-upnp-org:service:AVTransport:1",*groupVolume=@"urn:schemas-upnp-org:service:GroupRenderingControl:1";NSDictionary *instance=@{@"InstanceID":@0};SonosXMLNode *position=[self soap:@"GetPositionInfo" service:transport base:self.coordinatorURL arguments:instance],*status=[self soap:@"GetTransportInfo" service:transport base:self.coordinatorURL arguments:instance];if(!position||!status){self.deviceURL=nil;self.coordinatorURL=nil;self.nextDiscoveryAt=[NSDate dateWithTimeIntervalSinceNow:3];return @{@"error":@"Reconnecting to Sonos…"};}SonosXMLNode *metadata=ParseXML([Text(position,@"TrackMetaData")dataUsingEncoding:NSUTF8StringEncoding]);NSString *title=Text(metadata,@"title"),*artist=Text(metadata,@"creator"),*art=Text(metadata,@"albumArtURI");if(art.length)art=[NSURL URLWithString:art relativeToURL:self.coordinatorURL].absoluteURL.absoluteString?:@"";NSMutableDictionary *state=[@{@"room":self.room.length?self.room:@"Sonos",@"track":title.length?title:@"No music selected",@"artist":artist,@"art":art,@"playing":@([Text(status,@"CurrentTransportState")isEqual:@"PLAYING"]),@"toggle":@YES} mutableCopy];SonosXMLNode *volume=[self soap:@"GetGroupVolume" service:groupVolume base:self.coordinatorURL arguments:instance],*mute=[self soap:@"GetGroupMute" service:groupVolume base:self.coordinatorURL arguments:instance];if(volume){state[@"volume"]=@([Text(volume,@"CurrentVolume")integerValue]);state[@"slider"]=@YES;}if(mute)state[@"muted"]=@([Text(mute,@"CurrentMute")boolValue]);SonosXMLNode *actions=[self soap:@"GetCurrentTransportActions" service:transport base:self.coordinatorURL arguments:instance];NSArray *available=[Text(actions,@"Actions")componentsSeparatedByString:@","];NSMutableSet *supported=[NSMutableSet set];for(NSString *name in available)[supported addObject:[name stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceCharacterSet]];state[@"toggle"]=@([supported containsObject:[state[@"playing"]boolValue]?@"Pause":@"Play"]);if([supported containsObject:@"Previous"])state[@"previous"]=@YES;if([supported containsObject:@"Next"])state[@"next"]=@YES;return state; }
- (void)fetchState:(void (^)(NSDictionary *))completion { dispatch_async(self.worker,^{@autoreleasepool{NSDictionary *state=[self read];dispatch_async(dispatch_get_main_queue(),^{completion(state);});}}); }
- (void)performAction:(NSString *)action value:(NSNumber *)value completion:(void (^)(NSString *))completion { dispatch_async(self.worker,^{@autoreleasepool{NSString *error=nil;if(![self ensureDevice])error=@"Sonos is unavailable on this Wi-Fi";else{[self updateCoordinator];NSString *service=@"urn:schemas-upnp-org:service:AVTransport:1",*command=nil;NSMutableDictionary *args=[@{@"InstanceID":@0}mutableCopy];if([action isEqual:@"toggle"]){SonosXMLNode *status=[self soap:@"GetTransportInfo" service:service base:self.coordinatorURL arguments:args];if(!status)error=@"Could not read playback state";else{command=[Text(status,@"CurrentTransportState")isEqual:@"PLAYING"]?@"Pause":@"Play";if([command isEqual:@"Play"])args[@"Speed"]=@1;}}else if([action isEqual:@"next"])command=@"Next";else if([action isEqual:@"previous"])command=@"Previous";else if([action isEqual:@"volume"]&&value){service=@"urn:schemas-upnp-org:service:GroupRenderingControl:1";command=@"SetGroupVolume";args[@"DesiredVolume"]=@(MAX(0,MIN(100,value.integerValue)));}else if([action isEqual:@"mute"]){service=@"urn:schemas-upnp-org:service:GroupRenderingControl:1";SonosXMLNode *mute=[self soap:@"GetGroupMute" service:service base:self.coordinatorURL arguments:args];if(!mute)error=@"Could not read mute state";else{command=@"SetGroupMute";args[@"DesiredMute"]=@(![Text(mute,@"CurrentMute")boolValue]);}}if(!error&&(!command||![self soap:command service:service base:self.coordinatorURL arguments:args]))error=@"Sonos could not perform this action";}dispatch_async(dispatch_get_main_queue(),^{completion(error);});}}); }
@end
